### PR TITLE
remove validate delta

### PR DESCRIPTION
**Pull request by gogo2464**

### CODE REVIEW

**Comment by gogo2464** [comment]
it fails to build because `git push -f` does not seem to trigger a new cicd. Could you enable it on force push please? it is in yaml file

**Comment by gogo2464** [comment]
no my bad it is my fault

**Comment by gogo2464** [comment]
could you run tests please?

**Review by iduartgomez — APPROVED** [review]

**Comment by gogo2464** [comment]
nice!

**Pull request merged**
